### ISSUE TITLE
Update User

### ISSUE THREAD

**Issue by sylwiavargas** [sylwiavargas/The-Code-Bending-Dictionary#12]
**ADD:**
- a new migration: adding an `admin` (bool) and `username` (str) attributes in the Users table
<img width="817" alt="ERD" src="https://user-images.githubusercontent.com/45401242/94624695-4ed84880-02b7-11eb-864d-1f9b5f5825c6.png">
- a [method in the User model](https://dev.to/sylwiavargas/rails-backend-initializing-an-instance-with-a-default-value-5hb7) that makes the admin attribute default to `false` if nil

**UPDATE:**
- a new migration:  remove the `first_name`, `last_name`, `age` from the Users table
- update User model by removing the validations on the removed attributes and adding a `presence` and `uniqueness` validations on the `username`
- update the Users controller (params)

**Comment by naoufalelh** [comment]
Can you assigne this to me? I'm a first timer contributer and I saw you have good first time issues so I want to contirbute to this project for a good amount of time.

**Comment by naoufalelh** [comment]
Can we discuss why not use Devise gem to take care of authentification in this update. @sylwiavargas what do you think ?

**Comment by HyeokJungKim** [comment]
@naoufalelh 
Using Devise is something that we did think about, but ultimately decided against it for a few reasons.

>The dictionary was an idea of The Code Benders Cohort of Flatiron School's Immersive Software Engineering Program, and was developed initially as a part of Ruby and Ruby on Rails lectures.

When we initially started this project, we started it with the intention of making it accessible for people who are just beginning with Rails. We wanted the original users of the App to focus on just the core concepts of Rails before focusing on external gems, such as Devise. And since Devise has a LOT of features coming out of the box, which often overwhelms beginners and can get too unwieldy at times, we decided to just use bcrypt to lower the barrier for entry.

We also decided that this Rails app will be both an API and a web-app. Since Devise doesn't integrate too well with a Rails API and we'd have to use something else like Devise-JWT in place of Devise, we decided to keep it as it is.

**Comment by naoufalelh** [comment]
@HyeokJungKim Thank you for clarification about your decision. As I can tell it depends on the goal of the project, as you said if you want a newbie learning Rails to really understand how to use Rails features, you will need to make the authentification system yourself to teach them the basics about authentification. But in the other hand if you want to teach them the best practices and that it's very recommended to not build your own authentification system and use Devise as it's more secure and you won't as a beginner do any harm when you use it, then yes you will use it in this project.

Thanks again for your reply on the matter.

**Comment by sylwiavargas** [comment]
Hi @naoufalelh ! We have discussed it again and decided to go ahead with Devise (even though we do teach auth setup at FIS). Thank you for the points you brought up!

**Comment by naoufalelh** [comment]
@sylwiavargas Hello i will get back to this ASAP.

**Comment by sylwiavargas** [comment]
Hey @naoufalelh, we are scaling the project down and will now work only in our small team. If you are interested in the future developments of the project, I'll reach out to you when we accept contributions again!
